/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BinaryTree;

import javax.swing.JOptionPane;

/**
 *
 * @author Jeffrey
 */
public class Menu extends javax.swing.JFrame {

    int numeroMaxNodos = 0; //NODOS QUE GUARDARÁ
    int cantActualNodos = 0;
    
    Funciones fn = new Funciones();
    
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
                
        btnGuardarNodo.setEnabled(false);
        btnAltura.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantNodos = new javax.swing.JTextField();
        cantNodos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtNodo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtPreOrder = new javax.swing.JTextField();
        txtInOrder = new javax.swing.JTextField();
        txtPostOrder = new javax.swing.JTextField();
        btnAltura = new javax.swing.JButton();
        txtAltura = new javax.swing.JTextField();
        btnGuardarNodo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEliminarNodo = new javax.swing.JTextField();
        btnEliminarNodo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Árbol Binario");

        jLabel2.setText("Cantidad de Nodos");

        cantNodos.setText("Guardar");
        cantNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantNodosActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingresar Nodo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Recorridos del árbol");

        txtPreOrder.setEditable(false);

        txtInOrder.setEditable(false);

        txtPostOrder.setEditable(false);

        btnAltura.setText("Mostrar Altura del árbol");
        btnAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlturaActionPerformed(evt);
            }
        });

        txtAltura.setEditable(false);

        btnGuardarNodo.setText("Guardar");
        btnGuardarNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNodoActionPerformed(evt);
            }
        });

        jLabel5.setText("Eliminar Nodo");

        btnEliminarNodo.setText("Eliminar");
        btnEliminarNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarNodoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("PreOrder");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("InOrder");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("PostOrder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPreOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPostOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(txtNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarNodo)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEliminarNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarNodo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantNodos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cantNodos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAltura)
                        .addGap(26, 26, 26)
                        .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel4)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantNodos))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnGuardarNodo)
                    .addComponent(txtNodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtEliminarNodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarNodo))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPostOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantNodosActionPerformed
        try{
            numeroMaxNodos = Integer.parseInt(txtCantNodos.getText());
            
            //se guarda el nodo
            btnGuardarNodo.setEnabled(true);
            
            //no se permite cambiar cantidad de Nodos
            cantNodos.setEnabled(false);
            txtCantNodos.setEnabled(false);
            
            //se habilitan los demás botones
            btnAltura.setEnabled(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, String.format("Ingrese solo números enteros"),
                    "Ingrese cantidad de nodos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cantNodosActionPerformed

    private void btnGuardarNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNodoActionPerformed
        try{
            int numero = Integer.parseInt(txtNodo.getText());

            
            if (numeroMaxNodos >= cantActualNodos) {
                //se añade el nodo
                fn.add(numero);

                //se aumenta la cantidad de nodos
                cantActualNodos++;
                
                //se limpia el cammpo
                txtNodo.setText("");
                
                //SE IMPRIMEN LOS ÓRDENES DEL ÁRBOL/////////////
                
                //se limpian los campos
                txtInOrder.setText(null);
                //se limpia la lista antes de imprimirla
                fn.setListaIn("");
                //se recorre el arbol
                fn.inOrden(fn.root);
                txtInOrder.setText(fn.getListaIn());
                
                txtPreOrder.setText(null);
                //se limpia la lista de nodos para imprimir de nuevo
                fn.setListaPre("");
                //se recorre
                fn.preOrden(fn.root);
                txtPreOrder.setText(fn.getListaPre());
                
                txtPostOrder.setText(null);
                fn.setListaPost("");
                fn.postOrden(fn.root);
                txtPostOrder.setText(fn.getListaPost());
                
            }
            else{
                JOptionPane.showMessageDialog(null, String.format("No se pueden añadir más nodos"),
                        "Cantidad máxima de nodos alcanzados", JOptionPane.INFORMATION_MESSAGE);
            }
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, String.format("Ingrese solo números enteros"),
                    "Ingrese cantidad de nodos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarNodoActionPerformed

    private void btnAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlturaActionPerformed
        
        txtAltura.setText(null);
        
        int altura = fn.alturaArbol(fn.root);
        
        txtAltura.setText(String.valueOf(altura));
    }//GEN-LAST:event_btnAlturaActionPerformed

    private void btnEliminarNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarNodoActionPerformed
        try{
            int dato = Integer.parseInt(txtEliminarNodo.getText());
            
            //verifica que exista el nodo
            boolean existe = fn.buscaNodo(fn.root, dato);
            
            if(existe){
                fn.borrarNodo(dato);
                
                 //SE IMPRIMEN LOS ÓRDENES DEL ÁRBOL/////////////
                
                //se limpian los campos
                txtInOrder.setText(null);
                //se limpia la lista antes de imprimirla
                fn.setListaIn("");
                //se recorre el arbol
                fn.inOrden(fn.root);
                txtInOrder.setText(fn.getListaIn());
                
                txtPreOrder.setText(null);
                //se limpia la lista de nodos para imprimir de nuevo
                fn.setListaPre("");
                //se recorre
                fn.preOrden(fn.root);
                txtPreOrder.setText(fn.getListaPre());
                
                txtPostOrder.setText(null);
                fn.setListaPost("");
                fn.postOrden(fn.root);
                txtPostOrder.setText(fn.getListaPost());
                
                JOptionPane.showMessageDialog(null, "El nodo " + dato + " ha sido eliminado",
                    "Eliminar Nodo", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                 JOptionPane.showMessageDialog(null, "El nodo " + dato + " NO existe",
                    "Eliminar Nodo", JOptionPane.INFORMATION_MESSAGE);
            }
            
            txtEliminarNodo.setText(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese solo números enteros",
                    "Eliminar Nodo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarNodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltura;
    private javax.swing.JButton btnEliminarNodo;
    private javax.swing.JButton btnGuardarNodo;
    private javax.swing.JButton cantNodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtCantNodos;
    private javax.swing.JTextField txtEliminarNodo;
    private javax.swing.JTextField txtInOrder;
    private javax.swing.JTextField txtNodo;
    private javax.swing.JTextField txtPostOrder;
    private javax.swing.JTextField txtPreOrder;
    // End of variables declaration//GEN-END:variables
}
